- name: install httpd
  yum:
    name: httpd
    state: latest
- name: start and enable httpd
  service:
    name: httpd
    state: started
    enabled: yes
- name: create vhost direstory
    file:
      path: /var/www/vhosts/test.com/public_html
      state: directory
      mode: "0755"
      recurse: yes
- name: copy index.html
    copy:
      src: index.html
      dest: /var/www/vhosts/test.com/public_html
- name: copy test.com.conf
    copy:
      src: test.com.conf
      dest: /etc/httpd/conf.d/test.com.conf
    notify:
      - restart httpd